query getEverything($id: uuid!) {
  game: games_by_pk(id: $id) {
    id
    name
    pin_code
    game_type_id
    game_master_name
    finished
    started
    ua
    beers {
      id
      name
      number
      question
      type
      game_type_id
      game_id
      description
      correct_answer
      brewery_name
      country_name
      bid
      image
    }
    players {
      id
      game_id
      name
      score
      finished
    }
    beer_answers {
      beer_id
      game_id
      id
      question_content
      sort_order
    }
    player_answers {
      answer
      beer_id
      game_id
      player_id
      id
    }
  }
}
