query getGamePlayingData($id: uuid!, $player_id: Int_comparison_exp) {
  game: games_by_pk(id: $id) {
    id
    name
    game_type_id
    game_master_name
    finished
    pin_code
    started
    beers {
      id
      name
      number
      question
      type
      game_type_id
      game_id
      description
      brewery_name
      country_name
      bid
      image
    }
    players(where: { id: $player_id }) {
      id
      game_id
      name
      finished
      score
    }
    beer_answers {
      beer_id
      game_id
      id
      question_content
    }
    player_answers {
      answer
      beer_id
      game_id
      player_id
      id
    }
  }
}
