query getPlayer($id: Int!) {
  player: players_by_pk(id: $id) {
    id
    name
    score
    game_id
    finished
    created_at
    player_answers {
      id
      player_id
      game_id
      beer_id
      answer
    }
  }
}
